Add terminal parameters

diff --git a/progressbar b/progressbar
--- a/progressbar
+++ b/progressbar
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
 
 # Configuration
-TERMINAL="xfce4-terminal --hide-borders --geometry=x2+0+0 -x"
+TERMINAL="xfce4-terminal --title=Progressbar --hide-borders"
+TERMINAL+=" --geometry={c}x{r}+0+0 --zoom={z} -x"
 
 # Constants
 TIME_REG="(0?[0-9]|1[0-9]|2[0-3])(:(0?[0-9]|[1-5][0-9])(:(0?[0-9]|[1-5][0-9]))?)?"
@@ -9,13 +10,37 @@ BLOCKS=(" " "▏" "▎" "▍" "▌" "▋" "▊" "▉")
 
 # Main function
 main() {
+  # Parse parameters
+  local params; params="$(
+    getopt -q -o r:c:z:h -l rows:,cols:,zoom:,help -- "$@"
+  )" || abort 10 "Invalid options"
+  eval set -- "$params"
+
+  # Get options
+  local rows=2 cols=80 zoom=0
+  while [[ "$1" != "--" ]]; do
+    case "$1" in
+      -r | --rows ) shift; rows="$1";;
+      -c | --cols ) shift; cols="$1";;
+      -z | --zoom ) shift; zoom="$1";;
+      -h | --help ) usage; exit;;
+    esac
+    shift
+  done
+  shift
+
+  # Validate options
+  [[ "$rows" =~ ^[2-9]|[1-9][0-9]+$ ]] ||
+    abort 20 "Rows must be integer greater or equal to two"
+  [[ "$cols" =~ ^[4-9]|[1-9][0-9]+$ ]] ||
+    abort 20 "Cols must be integer greater or equal to four"
+  [[ "$zoom" =~ ^(-|\+)?[0-7]$ ]] ||
+    abort 20 "Zoom must be integer between -7 and 7"
+
   # Start in terminal if not already in one
   if [[ ! -t 1 ]]; then
-    exec $TERMINAL "$0" "$@"
+    start_terminal "$rows" "$cols" "$zoom" "$0" "$@"
   fi
-
-  # Print usage info if requested
-  [[ "$1" =~ ^help|-h|--help$ ]] && usage && exit
 
   # Get time specification
   local spec interactive
@@ -31,17 +56,19 @@ main() {
     # Read timestamps from user if interactive
     if $interactive; then
       read -rep "Time range: " -a spec
-      [[ "${spec[@]}" =~ ^exit|quit$ ]] && break
+      [[ "${spec[*]}" =~ ^exit|quit$ ]] && break
       history -s "${spec[*]}"
     fi
 
     # Get timestamps
-    local timestamps res; timestamps=( $(get_timestamps "${spec[@]}") )
+    local timestamps; timestamps=( $(get_timestamps "${spec[@]}") )
     case "$?" in
       101 )
-        echo >&2 "Invalid time range specification"
-        $interactive && continue || exit 1;;
-      100 ) echo >&2 "Exactly one or two parameters expected"; continue;;
+        echo >&2 "[Error] Invalid time range specification"
+        $interactive && continue || exit 25;;
+      100 )
+        echo >&2 "[Error] Exactly one or two parameters expected";
+        $interactive && continue || exit 25;;
       0   ) ;;
       *   ) exit "$?";;
     esac
@@ -56,13 +83,13 @@ main() {
 
 # Get times
 get_timestamps() {
-  # Check parameter count
+  # Validate parameter count
   (( $# == 1 || $# == 2 )) || return 100
 
   # Get start time
   local start
   if (( $# == 2 )); then
-    # Check start parameter format
+    # Validate start parameter format
     [[ "$1" =~ ^$TIME_REG$ ]] || return 101
 
     # Set to given time
@@ -73,7 +100,7 @@ get_timestamps() {
     start="$(date +%s)" || abort 50 "Getting current time failed"
   fi
 
-  # Check end parameter format
+  # Validate end parameter format
   [[ "$1" =~ ^\+?$TIME_REG$ ]] || return 101
 
   # Set absolute or relative end time
@@ -111,7 +138,7 @@ countdown() { local start="$1" end="$2"
     # Draw progressbar
     draw "$left" "$total"
 
-    # Wait for one second but abort countdown on escape
+    # Wait for one second but abort countdown on q or esc
     read -rst 1 -n 1 input
     [[ "$input" == $'\e' || "$input" == "q" ]] && break
   done
@@ -159,10 +186,26 @@ draw() { local left="$1" total="$2"
   echo -ne "$screen"
 }
 
+# Start terminal
+start_terminal() { local rows="$1" cols="$2" zoom="$3"; shift 3
+  # Construct terminal command
+  local command="$TERMINAL"
+  command="${command//"{r}"/$rows}"
+  command="${command//"{c}"/$cols}"
+  command="${command//"{z}"/$zoom}"
+
+  # Execute command
+  exec $command "$@" || abort 30 "Starting terminal failed"
+}
+
 # Print usage info
 usage() {
 cat <<END
-Usage: progressbar [[START] END]"
+Usage: progressbar [-r ROWS] [-c COLS] [-z ZOOM] [-h] [[START] END] 
+ -r, --rows   Set height of the terminal if opening one
+ -c, --cols   Set width of the terminal if opening one
+ -z, --zoom   Set zoom of the terminal if opening one
+ -h, --help   Show this help and exit
 
 Counts down to END, showing a graphical progressbar until q or esc is pressed.
 
@@ -175,6 +218,10 @@ plus, it is interpreted as a time of day.
 
 If no parameters are specified, the program runs in interactive mode and
 prompts the user for time specifications until they enter "exit" or "quit".
+
+The program checks if it is running in a terminal at startup and starts itself
+in an xfce4-terminal, if it doesn't. Feel free to specify another terminal
+emulator in the TERMINAL variable at the top of the program code.
 END
 }
 
